### ISSUE TITLE
Non idempotent behavior when combining wildcard and non-wildcard of same module

### ISSUE THREAD

**Issue by omertuc** [daixiang0/gci#100]
(I'm using GCI 0.6.2)

I like importing gomega and ginkgo like this:

```
	. "github.com/onsi/ginkgo"
	"github.com/onsi/ginkgo"
	"github.com/onsi/gomega"
	. "github.com/onsi/gomega"
```

This way I can be explicit and write things like:
`gomega.RegisterFailHandler(ginkgo.Fail)`

Instead of the more confusing:
`RegisterFailHandler(Fail)`

While still using compact assertions like:
`Expect(val.Payload.ReleaseTag).Should(Equal(""))`

Instead of this horrible verbosity:
`gomega.Expect(val.Payload.ReleaseTag).Should(gomega.Equal(""))`

But GCI doesn't play nice with this kind of import in some situations, depending on which other imports are present in the file. For instance:

```golang
package versions

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"testing"

	"github.com/go-openapi/swag"
	gomock "github.com/golang/mock/gomock"
	"github.com/kelseyhightower/envconfig"
	"github.com/onsi/ginkgo"
	. "github.com/onsi/ginkgo"
	"github.com/onsi/gomega"
	. "github.com/onsi/gomega"
	"github.com/openshift/assisted-service/internal/common"
	"github.com/openshift/assisted-service/internal/oc"
	"github.com/openshift/assisted-service/models"
	operations "github.com/openshift/assisted-service/restapi/operations/versions"
	"github.com/pkg/errors"
	"github.com/sirupsen/logrus"
	"github.com/thoas/go-funk"
	"gopkg.in/square/go-jose.v2/json"
	"gorm.io/gorm"
)
```

Run GCI and you get:
```golang
package versions

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"testing"

	"github.com/go-openapi/swag"
	gomock "github.com/golang/mock/gomock"
	"github.com/kelseyhightower/envconfig"
	. "github.com/onsi/ginkgo"
	"github.com/onsi/ginkgo"
	"github.com/onsi/gomega"
	. "github.com/onsi/gomega"
	"github.com/openshift/assisted-service/internal/common"
	"github.com/openshift/assisted-service/internal/oc"
	"github.com/openshift/assisted-service/models"
	operations "github.com/openshift/assisted-service/restapi/operations/versions"
	"github.com/pkg/errors"
	"github.com/sirupsen/logrus"
	"github.com/thoas/go-funk"
	"gopkg.in/square/go-jose.v2/json"
	"gorm.io/gorm"
)
```

Run it again and you get the first one again.

It just keeps switching between those two versions.

This is annoying because it means `golangci-lint` is telling me for one of them "not gci'd" + "not gofmt'd" and for the other one it's telling me "not gci'd" - there's nothing I can do to make `golangci-lint` happy here

The reason my example includes so many unrelated imports is that because without them, the issue doesn't reproduce! It's really weird. I tried to make it more minimal but the behavior was so unexpected I just pasted the original

**Comment by daixiang0** [comment]
I think https://github.com/daixiang0/gci/pull/99 will fix it, could you build and test at local?

**Comment by omertuc** [comment]
Sorry for duplicating #98.

Yes #99 does indeed fix the problem, thank you very much
