### ISSUE TITLE
Write produce invalid Go code

### ISSUE THREAD

**Issue by arxeiss** [daixiang0/gci#103]
**Version:** `0.6.3`
**Command:** `gci write -s standard -s default -s "prefix(github.com/...)" -s blank -s dot ./pkg ./proto ./services ./schema ./vendor ./cli`

For multiple reasons we need to use vendoring. And we wanted to sort imports in vendor folder too.
But that is causing issues with some files, which have multiple import statements. 

This is original file:
```go
import "C"
import (
	"unsafe"
)
```

and the output after running command:

```go
import "unsafe"

	"C"
)
```

Another example is this file: https://github.com/dgraph-io/ristretto/blob/4093c561df10415b3fe293e972f3c1c740734b37/z/calloc_jemalloc.go

```go
import "C"
import (
	"bytes"
	"fmt"
	"sync"
	"sync/atomic"
	"unsafe"

	"github.com/dustin/go-humanize"
)
```
and output
```go
import "bytes"
	"fmt"
	"sync"
	"sync/atomic"
	"unsafe"

	"C"
	"github.com/dustin/go-humanize"
)
```

**Comment by daixiang0** [comment]
It is "Cannot handle multiple imports group" from #86

**Comment by arxeiss** [comment]
Ah. I understood that badly. 

Is there some approach you would like to go? I think the easiest solution might be _Do not care about multiple imports, sort them separately_.

Because gofmt is joining if it is possible. And if not, I think this tool would just sort each import group as standalone import group.

**Comment by daixiang0** [comment]
I would like to ignore C import block, please ignore those files temporally, it will come in some days.
