### ISSUE TITLE
Support multiple prefixes to group them together and/or a regex

### ISSUE THREAD

**Issue by polds** [daixiang0/gci#107]
We have code hosted at `alt.code.company.com` and `code.company.com` It'd be nice to be able to provide `prefix(alt.code.company.com,code.company.com)` or a regular expression to match it.

So given:

```
import (
   "fmt"
   "github.com/daixiang0/gci"
   "code.company.com/foo/bar/baz"
   "alt.code.company.com/foo/boo"
)
```

The output of 

> gci write -s standard -s default -s 'Prefix(alt.code.company.com,code.company.com)' --custom-order --skip-generated .

Should yield:

```
import (
  "fmt"

  "github.com/daixiang0/gci"

  "alt.code.company.com/foo/boo"
  "code.company.com/foo/bar/baz"
)
```

**Comment by daixiang0** [comment]
Each custom group will be split, which is designed.
