### ISSUE TITLE
Checksum mismatch for v0.2.3

### ISSUE THREAD

**Issue by zikaeroh** [daixiang0/gci#11]
The most recently tagged release appears to not match what the Go sum database presents:

```
go: downloading github.com/daixiang0/gci v0.2.3
go get github.com/daixiang0/gci@upgrade: github.com/daixiang0/gci@v0.2.3: verifying module: checksum mismatch
	downloaded: h1:+mP3cW9wrL1wxE+2qqUt99Xx3eSM1lsqqOveAMZqA4A=
	sum.golang.org: h1:wg2R5t3NwFSmsGZDaD1mjiv0aRqktnaijE9f4SeLqu0=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

If you've force pushed (either commits or the tags), this will break the checksumming Go does to make sure that builds are reproducible and secure.

You may want to tag a v0.2.4 in order to make the latest version usable, as at the moment the latest version won't be importable by consumers like golangci-lint.

**Comment by daixiang0** [comment]
Fixed by v0.2.4 release.
