### ISSUE TITLE
gci not working s390x arch

### ISSUE THREAD

**Issue by irshadstars** [daixiang0/gci#114]
[root@api.acm27test.cp.fyre.ibm.com operator]# gci
-bash: gci: command not found
[root@api.acm27test.cp.fyre.ibm.com operator]# gci print -h
-bash: gci: command not found
[root@api.acm27test.cp.fyre.ibm.com operator]# uname -r
4.18.0-372.9.1.el8.s390x
[root@api.acm27test.cp.fyre.ibm.com operator]#

**Comment by daixiang0** [comment]
How do you install GCI?

**Comment by irshadstars** [comment]
i used to following 
[root@api.acm27test.cp.fyre.ibm.com operator]# go install github.com/daixiang0/gci@latest
[root@api.acm27test.cp.fyre.ibm.com operator]#

**Comment by daixiang0** [comment]
Could you put "GOPATH" under PATH env? The full path is like `$GOPATH/bin/gci`.

**Comment by irshadstars** [comment]
now gci  error fixed . gofumpt error occurred 
[root@api.acm27test.cp.fyre.ibm.com operator]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/bin:/root/go/bin
[root@api.acm27test.cp.fyre.ibm.com operator]# 
[root@api.acm27test.cp.fyre.ibm.com operator]# go env
GO111MODULE=""
GOARCH="s390x"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_s390x"
GOVCS=""
GOVERSION="go1.17.12"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/multicluster-global-hub/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3683764785=/tmp/go-build -gno-record-gcc-switches"
[root@api.acm27test.cp.fyre.ibm.com operator]# 
[root@api.acm27test.cp.fyre.ibm.com operator]# gci
Error: requires at least 1 arg(s), only received 0
Usage:
  gci [-diff | -write] [--local localPackageURLs] path... [flags]
  gci [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  diff        Prints a git style diff to STDOUT
  help        Help about any command
  print       Outputs the formatted file to STDOUT
  write       Formats the specified files in-place

Flags:
  -d, --diff            display diffs instead of rewriting files
  -h, --help            help for gci
  -l, --local strings   put imports beginning with this string after 3rd-party packages, separate imports by comma
  -v, --version         version for gci
  -w, --write           write result to (source) file instead of stdout

Use "gci [command] --help" for more information about a command.

[root@api.acm27test.cp.fyre.ibm.com operator]# 
[root@api.acm27test.cp.fyre.ibm.com operator]# make docker-build docker-push
/root/multicluster-global-hub/operator/bin/controller-gen rbac:roleName=multicluster-global-hub-operator-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/root/multicluster-global-hub/operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
GOFUMPT_SPLIT_LONG_LINES=on gofumpt -w ./main.go ./apis/ ./pkg/
bash: gofumpt: command not found
make: *** [Makefile:103: fmt] Error 127
[root@api.acm27test.cp.fyre.ibm.com operator]#

**Comment by daixiang0** [comment]
Sorry, `gofumpt ` is not maintained by me, seems that you also need to install it.
