### ISSUE TITLE
error with gci 0.8

### ISSUE THREAD

**Issue by hawkingrei** [daixiang0/gci#115]
### What version of GCI are you using?

<pre>
0.8.0
</pre>

### Reproduce Steps

<pre>
use tidb 
https://github.com/pingcap/tidb/pull/38320

make bazel_linter
</pre>

### What did you expect to see?

pass

### What did you see instead?

```
ERROR: /home/jenkins/.tidb/tmp/c81bba9845037d26d5cccd5f3ccb189e/external/com_github_gogo_protobuf/gogoproto/BUILD.bazel:3:11: GoCompilePkg external/com_github_gogo_protobuf/gogoproto/gogoproto.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/com_github_gogo_protobuf/gogoproto/doc.go -src ... (remaining 29 arguments skipped)


Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

compilepkg: nogo: errors found by nogo during build-time code analysis:

analyzer "gci" failed: 35:1: expected 'STRING', found 'func' (and 10 more errors)

```

**Comment by daixiang0** [comment]
Could you help locate which file lead this error?

**Comment by ice4026** [comment]
When I run the command `gci -w hello.go`, I got the similar issue: `Error: 4:1: expected 'STRING', found '(' (and 2 more errors)`, with the code in hello.go:

```
package main

import (
"log"
"code.s.org/a/be_test/app/demo"
"code.s.org/a/be_test/app/demo"
)

func main() {
}
```

**Comment by ice4026** [comment]
@daixiang0 One more case with v0.8.1, got error: `Error: 4:5: expected 'STRING', found '(' (and 4 more errors)`
```
package repo

import(
    "context"
    "code.s.org/a/be_test/app/demo/domain/demomodel"
)

type DemoRepo struct {
}

func (*DemoRepo) Get(ctx context.Context, id int64) (*demomodel.Demo, error) {
    // TODO your repo code here
    return &demomodel.Demo{}, nil
```

**Comment by daixiang0** [comment]
Now GCI assumes the source code is formatted, so you can format it first with help of IDE.

**Comment by ice4026** [comment]
@daixiang0 so would this case be fixed or just by design?

**Comment by daixiang0** [comment]
with #117 it is fixed.

**Comment by ice4026** [comment]
It's working correctly for me, just wonder if it could have a new tag :)

**Comment by daixiang0** [comment]
New tag comes ;)
