### ISSUE TITLE
Error: 19:1: expected 'STRING', found 'type' (and 10 more errors)

### ISSUE THREAD

**Issue by hawkingrei** [daixiang0/gci#119]
### What version of GCI are you using?

<pre>
gci version 0.8.2
</pre>

### Reproduce Steps

<pre>
git clone https://gitlab.com/cznic/sortutil.git
cd sortutil
gci write -s standard -s default sortutil.go

Error: requires at least 1 arg(s), only received 0
</pre>

### What did you expect to see?

not print error

### What did you see instead?

return error

**Comment by daixiang0** [comment]
Please try master HEAD, it would be fixed.

**Comment by hawkingrei** [comment]
I upgrade it in our CI and find new problems. gci enable write mode. it will remove comments and have a false-positive phenomenon.

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_build/detail/ghpr_build/5907/pipeline/91

**Comment by hawkingrei** [comment]
You can test it in tidb repo.

**Comment by daixiang0** [comment]
I see some format problems left over by history, now the failed file `testkit/testmain/bench.go` has been fixed.

To ensure no false-positive phenomenon, you can try `goimports` first then run `gci`.

**Comment by daixiang0** [comment]
@hawkingrei if no issues left, I will close it.
