### ISSUE TITLE
Support for stdin like goimports gofmt etc.

### ISSUE THREAD

**Issue by akarl** [daixiang0/gci#12]
These tools usually support reading from stdin.
This means that you can pipe the output through each tool.

For example `cat $file | goimports | gci -local "$(go list -m)" | gofmt -s` would do each tool in a row without writing to disk.

**Comment by cirocosta** [comment]
very useful for vim too:

```vim
" works perfectly
:%!goimports

" nope
:%!gci
```

**Comment by akarl** [comment]
I've actually made my own vim plugin for exactly that https://github.com/akarl/autoformat.nvim, I wanted something that **isn't** async and can run multiple formatters one after each other. The problem is that it uses stdin/stdout to be a bit faster and not use the disk after each format.
