### ISSUE TITLE
GCI fails to parse imports that are not in an import block

### ISSUE THREAD

**Issue by benmathews** [daixiang0/gci#121]
### What version of GCI are you using?

<pre>
gci version 0.8.2
</pre>

### Reproduce Steps

Running gci against the [attached file](https://github.com/daixiang0/gci/files/10014378/bad.go.txt) with imports individually specified. 

<pre>
❯ gci write bad.go 
Error: 12:148: expected ')', found 'EOF'
</pre>

Reformat the import lines and gci is able to parse the file.
[good.go](https://github.com/daixiang0/gci/files/10014375/good.go.txt)

<pre>
➜ diff bad.go good.go 
3,5c3,7
< import _ "source.vivint.com/pl/messagetypes/objectid"
< import _ "source.vivint.com/pl/messagetypes/time"
< import _ "source.vivint.com/pl/messagetypes/nullable"
---
> import (
> 	_ "source.vivint.com/pl/messagetypes/nullable"
> 	_ "source.vivint.com/pl/messagetypes/objectid"
> 	_ "source.vivint.com/pl/messagetypes/time"
> )
</pre>

**Comment by daixiang0** [comment]
You can use master HEAD to fix this issue.

**Comment by daixiang0** [comment]
Fixed by #120

**Comment by benmathews** [comment]
Sorry for the duplicate ticket. I reviewed open tickets, but not closed ones. Thanks for the fix.
