### ISSUE TITLE
Comment after imports gets removed

### ISSUE THREAD

**Issue by mhofstetter** [daixiang0/gci#123]
### What version of GCI are you using?

<pre>
v0.8.3
</pre>

### Reproduce Steps

Executing gci on the following source code removes the comment `// Test` on the struct which is following the imports.

It seems as the changed parsing logic is not respecting comments which might exist on a top level declaration: https://github.com/daixiang0/gci/blob/master/pkg/parse/parse.go#L115-L117

<pre>
package main

import (
	"fmt"
	_ "github.com/golang" // golang
	"github.com/daixiang0/gci"
)

// Test
type Test struct {
}
</pre>

-> 

<pre>
package main

import (
	"fmt"

	_ "github.com/golang" // golang

	"github.com/daixiang0/gci"
)

type Test struct {
}
</pre>

### What did you expect to see?

Only imports should be modified - comments of following declarations (e.g. structs) should not be removed.

### What did you see instead?

The comment of following declarations (e.g. structs) are getting removed.

**Comment by mhofstetter** [comment]
I saw that https://github.com/daixiang0/gci/pull/120 mentions the following

> introduce breaking change: remove isolated comments

but i don't think that this is an "isolated comment"

**Comment by daixiang0** [comment]
https://github.com/daixiang0/gci/pull/124 would fix this, thanks.
