### ISSUE TITLE
Add optional flag for ignoring `vendor` directory

### ISSUE THREAD

**Issue by artuross** [daixiang0/gci#129]
Currently, `gci` formats files stored in `vendor` directory. With vendoring enabled in a repository, it requires `gci` to be executed for example with `find` which is not suitable:

```sh
find . -type f -name '*.go' -not -path "./vendor/*" -exec gci write --skip-generated --custom-order -s 'standard,default' {} \;
```

I suggest to add another feature flag, similar to `--skip-generated` to natively ignore vendor directories: `--skip-vendor`.

**Comment by daixiang0** [comment]
Fixed by #139
