### ISSUE TITLE
no suggested fixes in analyzer report

### ISSUE THREAD

**Issue by SVilgelm** [daixiang0/gci#146]
Hi, I'm creating my own (yes, one more) [linter](https://github.com/sv-tools/gochecker) :) based on the [multichecker](https://pkg.go.dev/golang.org/x/tools/go/analysis/multichecker) and import `gci` as a lib, `pkg/analyzer`.
Everything works fine, the `GCI` provides an error message, but it does not provide the suggested fixes, so the files cannot be formatted automatically :-(

Could you please extend the analyzer to include the fixes as well?

Thank you!

### What version of GCI are you using?

<pre>
v0.9.1
</pre>

**Comment by daixiang0** [comment]
`golangci-lint` use this to fix, you can learn from it.

**Comment by SVilgelm** [comment]
I know about that approach, but it will not work in my case, I need the suggested fixes.
This sill take much longer, but I will need to create a wrapper on top of the `gci` analyzer to add the fixes.

**Comment by daixiang0** [comment]
Agree, you need to create a wrapper to get the fixes as golangci-lint does for many other linters.

If you are interested in optimizing it, I am happy to review it. Or I will label as won't fix and close since it is not a common requirement.

Thank you for choosing GCI!
