### ISSUE TITLE
Error when running gci against code with "\r\n"

### ISSUE THREAD

**Issue by inliquid** [daixiang0/gci#160]
### What version of GCI are you using?

<pre>
v0.10.1
</pre>

### Reproduce Steps

Run `gci` against code with "\r\n" instead of "\n" line ending. (This is common when f.e. some Go code is recovered using `git` with default config on Windows)

<pre>
>gci diff main.go   
Error: 4:12: expected ';', found "crypto/tls" (and 5 more errors)
</pre>

### What did you expect to see?

Diff showing misplaced imports.

### What did you see instead?
```
Error: 4:12: expected ';', found "crypto/tls" (and 5 more errors)
```

**Comment by daixiang0** [comment]
Fixed by #168
