### ISSUE TITLE
Comment for ignored import

### ISSUE THREAD

**Issue by sagikazarmark** [daixiang0/gci#18]
Given the following import section:

```
import (
    // ...
    _ "net/http/pprof" // register pprof HTTP handlers #nosec
)
```

gci tries to fix it as

```
import (
    // ...

    // register pprof HTTP handlers #nosec
    _ "net/http/pprof"
)
```

Is this on purpose? As far as I know it's a good practice to have a comment explaining why an import is being ignored and it's more readable on the same line.

**Comment by alecthomas** [comment]
It also moves the import to the stdlib for some reason:

```go
diff -u errors/errors.go.orig errors/errors.go
--- errors/errors.go.orig	2020-11-07 09:21:09.000000000 +1100
+++ errors/errors.go	2020-11-07 09:21:09.000000000 +1100
@@ -16,13 +16,15 @@
 package errors
 
 import (
+
+	// nolint: depguard
+	"github.com/pkg/errors" 
 	"context"
 	stderrors "errors"
 	"fmt"
 	"io"
 	"runtime"
 
-	"github.com/pkg/errors" // nolint: depguard
 	"google.golang.org/grpc/codes"
 	"google.golang.org/grpc/status"
```

**Comment by daixiang0** [comment]
It is a design for one line comment after import path, the extra line is a bug i think, i will fix it ASAP.

**Comment by kylechadha** [comment]
Bump. Running into this as well. 

```
import (
	"context"
	"crypto/md5" // nolint:gosec
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	"cloud.google.com/go/bigtable"
	"cloud.google.com/go/pubsub"
```

becomes
```
import (

	// nolint:gosec
	"crypto/md5" 
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	"cloud.google.com/go/bigtable"
	"cloud.google.com/go/pubsub"
```

Running `goimports` subsequently results in context and crypto/md5 being re-alphabeticized and now the `nolint` directive is on the wrong import. Would be great if `gci` did not affect inline comments, as I would also prefer to have them on the same line rather than above

Or perhaps this could be a configuration option :)

**Comment by daixiang0** [comment]
Now we have a configuration option for it.
