### ISSUE TITLE
math/rand/v2 not considered as standard library

### ISSUE THREAD

**Issue by tobischo** [daixiang0/gci#189]
### What version of GCI are you using?

<pre>
$ gci --version
gci version 0.12.3
</pre>

### Reproduce Steps

- Add math/rand/v2 to the code file see below
- Run `gci write --custom-order -s=standard -s="Prefix(some.specific.domain.com/prefix)" -s=default --skip-generated --skip-vendor .`

### What did you expect to see?
I expected `math/rand/v2` to be listed with the standard library packages and not with the other packages.

```go
import (
  "database/sql"
  "math/rand/v2"
  "testing"
  "time"

  _ "github.com/lib/pq"
)
```

### What did you see instead?
```go
import (
  "database/sql"
  "testing"
  "time"

  _ "github.com/lib/pq"
  "math/rand/v2"
)
```

**Comment by prochac** [comment]
It may be built with old version, using old std lib 
```
go version $(which gci)
```

try recompile it

**Comment by tobischo** [comment]
I completely removed gci and re-installed it. Re-opened all shells etc to make sure that it should be in a close to fresh environment with go 1.22.

I cannot recreate it anymore either. So you might have been correct that it must still have been something somehow running against 1.21.

Closing this.

Thank you for checking and sorry for the additional work
