### ISSUE TITLE
Something wrong with version 0.13.2

### ISSUE THREAD

**Issue by fongfiafia** [daixiang0/gci#198]
### What version of GCI are you using?
0.13.2

<pre>

</pre>

### Reproduce Steps
My makefile  command is: go install github.com/daixiang0/gci@latest. This usually works fine, but yesterday I encountered an error:

go: github.com/daixiang0/gci@latest (in github.com/daixiang0/gci@v0.13.2): go.mod:5: unknown directive: toolchain

I believe the error was caused by changes introduced in the latest version of the package. So to resolve it, I instead specified a previous stable version by changing the command to:

go install github.com/daixiang0/gci@v0.13.1

and the problem is solved. 

<pre>

</pre>

**Comment by daixiang0** [comment]
Thanks for your report!

The root cause is Go 1.22 introduce this param in the go module, I will delete it and release new version for backwards compatible.

**Comment by fongfiafia** [comment]
您好，来件已收到，我会尽快给您回复。
