### ISSUE TITLE
Multiple prefix() sections should not be automatically sorted

### ISSUE THREAD

**Issue by SOF3** [daixiang0/gci#205]
### What version of GCI are you using?

<pre>
0.13.4
</pre>

### Reproduce Steps

```console
$ example.go
package example

import (
        _ "example.com/a/b"
        _ "example.com/i/j"
        _ "example.com/m/n"
        _ "example.com/p/q"
)

$ go run github.com/daixiang0/gci@v0.13.4 print example.go \
>       -s standard
>       -s default
>       -s 'prefix(example.com/i/j,example.com/m/n)'
>       -s 'prefix(example.com/a/b,example.com/p/q)'
package example

import (
        _ "example.com/a/b"
        _ "example.com/p/q"

        _ "example.com/i/j"
        _ "example.com/m/n"
)
```

### What did you expect to see?

The sections should be consistent with the order of `-s`s passed.

### What did you see instead?

The sections follow lexicographical order of the `prefix()` string. If I change the fourth section to `prefix(example.com/p/q,example.com/a/b)`, the two sections in the output will be swapped.

**Comment by SOF3** [comment]
Possible workaround for now: adding `nosuchmodule/1,` and `nosuchmodule/2,` after `prefix(` to force the order of prefixes.

**Comment by daixiang0** [comment]
The two prefix section does not follow lexicographical order which is written in the README, the strings in the prefix follow, so you can put then into one prefix section.

I think it is good to improve, you can take it if interested.

Label it as `help wanted` if someone else interested.

**Comment by SOF3** [comment]
I don't understand. What is written in the readme?

**Comment by DanWlker** [comment]
Hi, can i have a go on this issue? Is a flag required to enable this behaviour? or can we set ordering based on the sequence of -s passed into the cli call as a default

**Comment by asfaltboy** [comment]
I came across this issue, and I was missing the "--custom-order" flag, @SOF3 are you providing it?

It seems to be required when sections are given, otherwise sections are sorted alphabetically.

I found it a tad confusing, and it took me a while to figure out that without it, just adding sections in a given order has no impact on order of sections.
