### ISSUE TITLE
import package questions

### ISSUE THREAD

**Issue by gy95** [daixiang0/gci#36]
when i import packages as the following, cannot pass the gci check
```
import (
	_ "crypto/sha256" // initialize crypto/sha256 to enable sha256 algorithm
	_ "crypto/sha512" // initialize crypto/sha512 to enable sha512 algorithm
	"strings"

	"github.com/distribution/distribution/v3/reference"
)
```

but when i modify the format to the following, it can pass the gci check

```
import (

	// initialize crypto/sha256 to enable sha256 algorithm
	_ "crypto/sha256"

	// initialize crypto/sha512 to enable sha512 algorithm
	_ "crypto/sha512"
	"strings"

	"github.com/distribution/distribution/v3/reference"
)
```

is this verification reasonable? 
comments of the import package should be preceded by a blank line, 
and the comments and the imported packages cannot be on the same line

**Comment by daixiang0** [comment]
It is a design that `gci` always split comment and pkg path.

Sort issue would be fixed soon.
