### ISSUE TITLE
Please, support inline "// nolint:..." comments

### ISSUE THREAD

**Issue by ashumkin** [daixiang0/gci#37]
I have a project using `sha1` package. And multiple linters checks are run against the project.
`gosec` linter warns about the `sha1` package usage, but I do not plan to change the package, so I want to suppress the warning with the "// nolint:gosec" inline comment,
```golang
	"crypto/sha1" // nolint:gosec
```
 after that the `gci` linter check produces the error about the sources that are not `gci`-ed.
After passing the sources through `gci` (which moves the inline comment up to the previous line),
```golang
	// nolint:gosec
	"crypto/sha1"
```
Now `gosec` linter complains again.

The deadlock/deadloop...

How to make both linters happy?

**Comment by daixiang0** [comment]
Would support later.

**Comment by AlekSi** [comment]
Assuming that @ashumkin uses golangci-lint for `//nolint`, I think the better fix would be to report errors on the right line. Then something like that should work:
```go
import (
    "crypto/hmac"
    "crypto/sha1" //nolint:gci,gosec
    "net/url"
    "sort"
)
```
