### ISSUE TITLE
Separate local packages from 3rd party with newline?

### ISSUE THREAD

**Issue by jh125486** [daixiang0/gci#38]
My normal company policy is "standard lib/company packages/3rd party" groups, each separated by newlines.   
Basically "most" to "least" trusted packages.
I see that I can define "local" packages from 3rd party packages so they are at the end, but is there a way have a new line between them? e.g.

```go
import (
	"bytes"

	"github.com/aws/aws-sdk-go-v2/aws"

	"awesomeLocalEnterpriseGit.company.com/pkg1"
)
```

**Comment by daixiang0** [comment]
It is kindly of multiple imports support, would support soon.

**Comment by daixiang0** [comment]
Support multiple prefix:
sections:
  - Standard
  - Prefix(github.com/local)
  - Prefix(github.com/daixiang0)
