### ISSUE TITLE
What's the meaning of 'local'?

### ISSUE THREAD

**Issue by wymli** [daixiang0/gci#40]
Normally, these imported pkgs should be seen as three categories: 
1. built-in pkg
2. in-this-pkg dependency 
3. 3rd external dependency
they will be seperated by newline, from top to down.

I noticed that `'-local $prefix'` will make the pkgs beginning with the `$prefix` the bottom of the import block.
But from the first the view, I would think `'local'` means `in-this-pkg dependency`

fix me, Please!

**Comment by daixiang0** [comment]
It is same as `goimports`.
