### ISSUE TITLE
"skip file since no import" output breaks use-case of outputting to stdout

### ISSUE THREAD

**Issue by danxmoran** [daixiang0/gci#42]
After #41 merges I was hoping to be able to use `gci` as part of a chain of formatting tools, roughly:
```
gofmt main.go | gci > main.formatted.go
```
This use-case doesn't work for files with no imports, because `gci` prints "skip file main.go since no import" to stdout instead of the contents of the file.

It would be better if the "skip file" message was printed to stderr instead of stdout. If `-w` is passed the tool can still bail out early, but if `-w` is missing then the file contents should still be printed to stdout.

**Comment by daixiang0** [comment]
Fixed.
