### ISSUE TITLE
GCI is way too verbose

### ISSUE THREAD

**Issue by t-botz** [daixiang0/gci#46]
With the new version I have a massive output like 
```go
$ find . -name '*.go' | xargs gci write

// ...
2022/02/07 09:54:53 Loaded File: pkg/query/products_test.go
2022/02/07 09:54:53 Skipping correctly formatted File: cmd/refresh_contentful/query_merchants_test.go
2022/02/07 09:54:53 Skipping correctly formatted File: cmd/http/main_test.go
2022/02/07 09:54:53 Skipping correctly formatted File: pkg/resource/utils.go
2022/02/07 09:54:53 Loaded File: pkg/query/params.go
2022/02/07 09:54:53 Skipping correctly formatted File: pkg/resource/product.go
2022/02/07 09:54:53 Skipping correctly formatted File: pkg/query/search_image.go
2022/02/07 09:54:53 Skipping correctly formatted File: pkg/graphql/relay/connection_test.go
// ...
```

Also it goes to stderr, so I can't even choose to only showing errors by piping stdout to `/dev/null`. I think all those things should be part of debug and in stdin.

**Comment by daixiang0** [comment]
It would be better to add those into debug and split stdin from stderr.

**Comment by t-botz** [comment]
I'll raise a PR

**Comment by t-botz** [comment]
@daixiang0 Are you open to adding a logging library? I am thinking about https://github.com/uber-go/zap

**Comment by daixiang0** [comment]
I think the native log library is enough, does it have some special features that we need?

**Comment by daixiang0** [comment]
Sounds great, let's do it.
