### ISSUE TITLE
"Error: an error occured while trying to parse imports: path is missing starting quotes" on valid Go file

### ISSUE THREAD

**Issue by charleskorn** [daixiang0/gci#48]
If I have a file that contains this content: 

```go
package main

import (
	/*
		#include "types.h"
	*/
	"C"
)
```

...and invoke `gci` with `gci diff --debug file.go`, I get this error:

```
2022/03/01 11:42:07 Loaded File: file.go
Error: an error occured while trying to parse imports: path is missing starting quotes
```

Is this expected? I can't see what the issue is.

Removing the `/* ... */` causes `gci` to not fail with an error, but I can't remove that comment as cgo relies on it.

**Comment by daixiang0** [comment]
Yes, it is truly a bug with CGO, someone interested in fixing it need to add a check for CGO part and skip them.

**Comment by charleskorn** [comment]
Do you have any pointers on where to start to fix this @daixiang0?

**Comment by daixiang0** [comment]
`parseToImportDefinitions` in pkg/gci/parse.go.
