### ISSUE TITLE
gci error not clear

### ISSUE THREAD

**Issue by georgettica** [daixiang0/gci#59]
the error https://github.com/daixiang0/gci/blob/73cde2312b7818a42a260f2d49085e3a3cd456a0/pkg/analyzer/analyzer.go#L93

jumped for me when I had

```
import (
        "fmt"
        "reflect"

        "github.com/go-pg/pg/v10"
        "github.com/go-pg/pg/v10/orm"

        "github.com/spf13/cobra"
)
```
and the fix was to join the 3 github imports.

could we catch this error up somewhere so the error would be more along the lines "imports are not joined together, please remove newline in line X" ?

the error is
```
file.go:X:${LAST_CHAR_IN_LINE}: Expected '\t', Found '\n' at file.go[line X col ${LAST_CHAR_IN_LINE}] (gci)

**Comment by KenjiTakahashi** [comment]
I've just added `gci` to my `golangci-lint` config and immediately got a bunch of errors like this:
```
Expected 'u', Found '"' at user.go[line 27,col 2]
```
```
Expected 'g', Found 'b' at processor.go[line 9,col 3]
```
```
Expected '"', Found 's' at main.go[line 10,col 2]
```
Etc.

It could really use a more readable error message, at first I thought the integration is just broken.

**Comment by ngehrsitz** [comment]
@georgettica The error reporting in gci is an area that could definitely improved. Until that happens I would recommend that you run gci in write mode to see what output gci expects.

**Comment by daixiang0** [comment]
You can try latest version :)

**Comment by georgettica** [comment]
I will do that soon and report back, thanks!
