### ISSUE TITLE
Suggestion: Change or allow optional flag to accept inline comments for imports

### ISSUE THREAD

**Issue by heedson** [daixiang0/gci#6]
An example in a migration source file is as follows (pre-gci run):
```
import (
	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/postgres" // database migration drivers
	_ "github.com/golang-migrate/migrate/v4/source/file"       // database migration drivers
	_ "github.com/lib/pq"                                      // database drivers
	"github.com/pkg/errors"
)
```

When `_` a import, it requires a comment, for good reason. However, gci dictates that the comments should be above the imports, however that isn't adequate when changed simply to the following:
```
import (
	"github.com/golang-migrate/migrate/v4"
	// database migration drivers
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	// database migration drivers
	_ "github.com/golang-migrate/migrate/v4/source/file"
	// database drivers
	_ "github.com/lib/pq"
	"github.com/pkg/errors"
)
```
This isn't what gci wants either. Fixing it to be gci compliant:
```
import (
	"github.com/golang-migrate/migrate/v4"

	// database migration drivers
	_ "github.com/golang-migrate/migrate/v4/database/postgres"

	// database migration drivers
	_ "github.com/golang-migrate/migrate/v4/source/file"

	// database drivers
	_ "github.com/lib/pq"
	"github.com/pkg/errors"
)
```
Perhaps it's just personal opinion, but when there are multiple comments required in the import block, it looks a lot more readable and concise to allow for them to be inline. If a comment requires a new line above them, it indicates to me that the following **block** of imports all pertain to that comment and not just the one directly below it (e.g. ".../pkg/errors" isn't a database driver).

I would love to hear opinions on this for one way or another.

**Comment by daixiang0** [comment]
Now we have new option for it, you can try latest version if you want, thanks.
