### ISSUE TITLE
errors when using import alias, zap package since version 0.3.0

### ISSUE THREAD

**Issue by brandon-lango** [daixiang0/gci#60]
We are using gci as part of golangci-lint. Ever since version 0.3.0, we have been getting errors where previous versions have worked.

This error seems like it's expecting everything to import from github.com, however we use zap which comes from go.uber.org.

 **Expected 'i', Found 'o'** 
`"go.uber.org/zap"`

We also get this, which seems to be related to using aliases

**Expected '"', Found 'l'** 
`log "github.com/sirupsen/logrus"`

This version also seems to not like blank lines between our third party libraries and internal imports.
**Expected '\t', Found '\n'**

**Comment by daixiang0** [comment]
Could you try latest version?

**Comment by brandon-lango** [comment]
> Could you try latest version?

I'm using the latest version of golangci-lint, which includes gci 0.3.2.  https://github.com/golangci/golangci-lint/pull/2640

I'm not sure when they will update to 0.3.3, but it doesn't look like that version has fixes for these issues.

**Comment by ngehrsitz** [comment]
@brandon-lango Could you please specify the exact command that you ran gci with and upload the affected files so that I can try to reproduce the issue. Only the import section is relevant you can remove everything else.

**Comment by brandon-lango** [comment]
Here are a few examples. It seems to fail everywhere there is an import alias or we use the zap package. I'm running gci as a part to golangci-lint, not as a standalone command. We are using all the default settings for gci. 

Expected 'i', Found 'o' at pkg/mt/infra/providers/onedrive/download.go[line 9,col 4] (gci)
        "go.uber.org/zap"

```
import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"sync"

	"go.uber.org/zap"
)
```

Expected '\t', Found '\n' at pkg/mt/infra/providers/externalstorage/goroutines.go[line 5,col 1] (gci)

```
import (
	"github.com/hashicorp/go-multierror"

	mtCommand "github.com/langomobiledev/lango/pkg/mt/app/command"
	"github.com/langomobiledev/lango/pkg/mt/domain/filestorage"
)
```

 Expected '"', Found 'l' at pkg/auth/infra/providers/cognito/register.go[line 11,col 2] (gci)
        log "github.com/sirupsen/logrus"


```
import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	cognito "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
	log "github.com/sirupsen/logrus"

	"github.com/langomobiledev/lango/pkg/auth/domain/users"
)
```

**Comment by daixiang0** [comment]
Please add prefix to test.

**Comment by NicklasWallgren** [comment]
I've got this issue as well with golangci-lint v1.46.2

```
infrastructure/database/database.go:7:2: Expected '"', Found 'g' at infrastructure/database/database.go[line 7,col 2] (gci)
        gormTrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/gorm.io/gorm.v1"
        ^
```
