### ISSUE TITLE
Regression in golangci-lint

### ISSUE THREAD

**Issue by howardjohn** [daixiang0/gci#61]
We recently update golangci-lint and it broke gci, forcing us to disable it.

To reproduce:

https://github.com/istio/istio/commit/3a245f843d38a5598b171a18422a09b4b1ba0802

```
$ golangci-lint run --fix -c ./common/config/.golangci-format.yml istioctl/pkg/util/proto/messageslice.go
istioctl/pkg/util/proto/messageslice.go:21:1: Expected '\t', Found '\n' at istioctl/pkg/util/proto/messageslice.go[line 21,col 1] (gci)

^
```

Can also run in our docker build:
```
./common/scripts/run.sh golangci-lint run --fix -c ./common/config/.golangci-format.yml istioctl/pkg/util/proto/messageslice.go
```

**Comment by daixiang0** [comment]
@howardjohn thanks for the report! Now, which version of golangci-lint do you use? I will investigate that version first.

**Comment by ivila** [comment]
> @howardjohn thanks for the report! Now, which version of golangci-lint do you use? I will investigate that version first.

reproduce at golangci-lint 1.46.2

**Comment by daixiang0** [comment]
https://github.com/golangci/golangci-lint/pull/2892 I think need to wait next fix version.

**Comment by daixiang0** [comment]
@howardjohn please try the latest version :)

**Comment by daixiang0** [comment]
@ivila please wait for the next release, 1.46.2 is released on May 17, but the fix PR is merged on May 31.
