### ISSUE TITLE
Group dot imports

### ISSUE THREAD

**Issue by avorima** [daixiang0/gci#65]
AFAICT gci is not able to group dot imports together. It would be nice to be able to configure this.

**Comment by daixiang0** [comment]
Do you mean below:
```
import(
  "fmt"

  _ "xxx1"

  _ "xxx2"
)
```

to 
```
import(
  "fmt"

  _ "xxx1"
  _ "xxx2"
)
```
?

**Comment by avorima** [comment]
Almost, I mean

```go
import (
        "fmt"

        . "foo"

        . "bar"
        "baz"
)
```
to
```go
import (
        "fmt"

        . "bar"
        . "foo"

        "baz"
)
```

I think package prefix could still work the hierarchy just has to be defined. If there's an explicit "dot" group then I would expect that to have more priority than a package prefix.

**Comment by mnencia** [comment]
I second that. I would like to have all the ginkgo and gomega dot imports in my unit tests at the end of the import lists.
