### ISSUE TITLE
How to skip some files when run gci

### ISSUE THREAD

**Issue by wuyingjun-lucky** [daixiang0/gci#69]

**Comment by wuyingjun-lucky** [comment]
@daixiang0 

I part my imports to three sections and In some file I need to part into four because some package should be initialized before others. 
How to resolve this sistuation or can we ignore some files ?

**Comment by daixiang0** [comment]
You can use `--Section` to part into different sections.

**Comment by daixiang0** [comment]
@wuyingjun-lucky if not help, please provide more details,

**Comment by wuyingjun-lucky** [comment]
> @wuyingjun-lucky if not help, please provide more details,

sorry ，I  have resolve it 
Thank you 
/close
