### ISSUE TITLE
Prefixes with capital letters are ignored

### ISSUE THREAD

**Issue by SamCHogg** [daixiang0/gci#79]
With the following config:
```
sections:
  - Standard
  - Default
  - Prefix(github.com/Azure)
```

I would expect that the imports are formatted as so:
```
import (
	"fmt"

	"github.com/golang"

	"github.com/Azure/go-autorest/autorest"
)
```

However, as of v0.4.0 it appears that having a capital letter in the prefix, in this case the `A` in `Azure`, results in the prefix being ignored. So instead I am getting:
```
import (
	"fmt"

	"github.com/Azure/go-autorest/autorest"
	"github.com/golang"
)
```

**Comment by ldez** [comment]
Hello, I created a fix #81
