### ISSUE TITLE
Running error: gci: failed to diff: exec: \"diff\": executable file not found in $PATH

### ISSUE THREAD

**Issue by SVilgelm** [daixiang0/gci#8]
Hi,
I'm using a custom docker files, that does not contain a `diff` tool, and the `golangci-lint` fails with an error:
```
level=warning msg="[runner] Can't run linter goanalysis_metalinter: gci: failed to diff: exec: \"diff\": executable file not found in $PATH"
level=error msg="Running error: gci: failed to diff: exec: \"diff\": executable file not found in $PATH"
```
Please get rid of usage the `diff` tool, please use the `github.com/shazow/go-diff/difflib` library, example of ho to use it you can find here: https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/gofumpt.go#L62

**Comment by SVilgelm** [comment]
Instead of this: https://github.com/daixiang0/gci/blob/master/pkg/gci/gci.go#L178-L198

you can do like this:
```go
	out := bytes.Buffer{}
	_, err = out.WriteString(fmt.Sprintf("--- %[1]s\n+++ %[1]s\n", f))
	if err != nil {
		return nil, fmt.Errorf("error while running gofumpt: %w", err)
	}
	err = differ.Diff(&out, bytes.NewReader(b1), bytes.NewReader(b2))
	if err != nil {
		return nil, fmt.Errorf("error while running gofumpt: %w", err)
	}
	return out.Bytes()
```

**Comment by SVilgelm** [comment]
and least it will be faster, then using a subcommand

**Comment by daixiang0** [comment]
Goimports still call `diff`, need to dig deeper.

**Comment by SVilgelm** [comment]
I would prefer to turn off `goimports` than `gci`  :)

**Comment by daixiang0** [comment]
Thanks!

While I do not want any extra pkg here, so i would update `gci.Run` and the way to call in golang-ci.

**Comment by SVilgelm** [comment]
thank you for the quick fix!!!!
