### ISSUE TITLE
Duplicate imports are reordered back and forth (`gci write` not idempotent)

### ISSUE THREAD

**Issue by barrettj12** [daixiang0/gci#98]
I am using gci to format [this Go file](https://github.com/juju/juju/blob/41a6baeb0c4c6c76891847aa72deb08f44aacd4e/cmd/juju/romulus/sla/sla_test.go). Note that it has duplicate imports:
```go
import (
        ...
	"github.com/juju/testing"
	jujutesting "github.com/juju/testing"
        ...
)
```
When I run
```
gci write -s standard -s default -s "Prefix(github.com/juju/juju)" --skip-generated \
  cmd/juju/romulus/sla/sla_test.go
```
it will continue to reorder these imports. i.e. after one run they will be in the reverse order
```go
import (
        ...
	jujutesting "github.com/juju/testing"
	"github.com/juju/testing"
        ...
)
```
If I run it again, they will return to the original order. If I run it again, they will reverse again, and so forth.

This is observed on gci v0.6.2. Obviously I would expect `gci write` to be idempotent. I am struggling to isolate a MWE - I've tried a few simpler Go files and haven't observed this behaviour.

**Comment by daixiang0** [comment]
@barrettj12  Thanks for your report! It is a very special case, since deduplication is still a known issue, let me think about the solution.

**Comment by barrettj12** [comment]
This is the most minimal working example I could get:
```go
package sla_test

import (
	"github.com/juju/testing"
	jujutesting "github.com/juju/testing"
	jc "github.com/juju/testing/checkers"
	gc "gopkg.in/check.v1"
	"gopkg.in/macaroon.v2"

	"github.com/juju/juju/api"
	"github.com/juju/juju/jujuclient"
)

type supportCommandSuite struct {
	jujutesting.CleanupSuite
}

func (s *supportCommandSuite) TestDiplayCurrentLevel(c *gc.C) {
	c.Assert("", jc.ErrorIsNil)
}

type mockapi struct {
	testing.Stub
	macaroon *macaroon.Macaroon
}

type fakeAPIConnection struct {
	api.Connection
}

type mockClientStore struct {
	jujuclient.ClientStore
}
```

**Comment by daixiang0** [comment]
@barrettj12 please try #99 at local.

**Comment by barrettj12** [comment]
Seems to have fixed it, thanks!
